import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Mint from "../components/Mint";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fox NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Mint></Mint>
    </div>
  );
}
